In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/Dataset_ATS_v2.csv")

In [3]:
df.head()

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges,Churn
0,Female,0,No,1,No,No,DSL,Month-to-month,25,Yes
1,Male,0,No,41,Yes,No,DSL,One year,25,No
2,Female,0,Yes,52,Yes,No,DSL,Month-to-month,19,No
3,Female,0,No,1,Yes,No,DSL,One year,76,Yes
4,Male,0,No,67,Yes,No,Fiber optic,Month-to-month,51,No

In [4]:
df.shape

(7043, 10)

In [5]:
df.columns.tolist()

['gender',
 'SeniorCitizen',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'Contract',
 'MonthlyCharges',
 'Churn']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gender           7043 non-null   str
 1   SeniorCitizen    7043 non-null   int64
 2   Dependents       7043 non-null   str
 3   tenure           7043 non-null   int64
 4   PhoneService     7043 non-null   str
 5   MultipleLines    7043 non-null   str
 6   InternetService  7043 non-null   str
 7   Contract         7043 non-null   str
 8   MonthlyCharges   7043 non-null   int64
 9   Churn            7043 non-null   str
dtypes: int64(3), str(7)
memory usage: 775.3 KB

In [7]:
df.isnull().sum()

gender             0
SeniorCitizen      0
Dependents         0
tenure             0
PhoneService       0
MultipleLines      0
InternetService    0
Contract           0
MonthlyCharges     0
Churn              0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(302)

In [9]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.758768
std         0.368612    24.559481       30.091650
min         0.000000     0.000000       18.000000
25%         0.000000     9.000000       36.000000
50%         0.000000    29.000000       70.000000
75%         0.000000    55.000000       90.000000
max         1.000000    72.000000      119.000000

In [10]:
df.describe(include="all")

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges,Churn
count,7043,7043.000000,7043,7043.000000,7043,7043,7043,7043,7043.000000,7043
unique,2,NaN,2,NaN,2,2,2,3,NaN,2
top,Male,NaN,No,NaN,Yes,No,DSL,Month-to-month,NaN,No
freq,3555,NaN,4933,NaN,6361,4072,3947,3875,NaN,5174
mean,NaN,0.162147,NaN,32.371149,NaN,NaN,NaN,NaN,64.758768,NaN
std,NaN,0.368612,NaN,24.559481,NaN,NaN,NaN,NaN,30.091650,NaN
min,NaN,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,18.000000,NaN
25%,NaN,0.000000,NaN,9.000000,NaN,NaN,NaN,NaN,36.000000,NaN
50%,NaN,0.000000,NaN,29.000000,NaN,NaN,NaN,NaN,70.000000,NaN
75%,NaN,0.000000,NaN,55.000000,NaN,NaN,NaN,NaN,90.000000,NaN
max,NaN,1.000000,NaN,72.000000,NaN,NaN,NaN,NaN,119.000000,NaN

In [11]:
df.isnull().sum().sort_values(ascending=False)

gender             0
SeniorCitizen      0
Dependents         0
tenure             0
PhoneService       0
MultipleLines      0
InternetService    0
Contract           0
MonthlyCharges     0
Churn              0
dtype: int64

In [12]:
df[df.duplicated()].head()

,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,MonthlyCharges,Churn
78,Male,0,No,1,Yes,No,DSL,Month-to-month,20,No
97,Male,0,No,1,Yes,No,DSL,Month-to-month,20,No
352,Male,0,No,1,Yes,No,Fiber optic,Month-to-month,20,No
398,Male,0,No,1,Yes,No,DSL,Month-to-month,20,No
402,Male,0,No,1,Yes,Yes,Fiber optic,Month-to-month,20,Yes

In [13]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n--- {col} ---")
    print(df[col].nunique(), "unique values")
    print(df[col].value_counts(dropna=False).head(10))

--- gender ---
2 unique values
gender
Male      3555
Female    3488
Name: count, dtype: int64

--- Dependents ---
2 unique values
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

--- PhoneService ---
2 unique values
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

--- MultipleLines ---
2 unique values
MultipleLines
No     4072
Yes    2971
Name: count, dtype: int64

--- InternetService ---
2 unique values
InternetService
DSL            3947
Fiber optic    3096
Name: count, dtype: int64

--- Contract ---
3 unique values
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

--- Churn ---
2 unique values
Churn
No     5174
Yes    1869
Name: count, dtype: int64

/var/folders/fr/c6p38rg92qx5f6s8cskzn4v80000gn/T/ipykernel_27497/368808252.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [14]:
df.columns

Index(['gender', 'SeniorCitizen', 'Dependents', 'tenure', 'PhoneService',
       'MultipleLines', 'InternetService', 'Contract', 'MonthlyCharges',
       'Churn'],
      dtype='str')

In [15]:
df.columns = (
    df.columns.str.strip()
              .str.lower()
              .str.replace(" ", "_")
              .str.replace(r"[^a-zA-Z0-9_]", "", regex=True)
)
df.columns.tolist()

['gender',
 'seniorcitizen',
 'dependents',
 'tenure',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'contract',
 'monthlycharges',
 'churn']

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gender           7043 non-null   str
 1   seniorcitizen    7043 non-null   int64
 2   dependents       7043 non-null   str
 3   tenure           7043 non-null   int64
 4   phoneservice     7043 non-null   str
 5   multiplelines    7043 non-null   str
 6   internetservice  7043 non-null   str
 7   contract         7043 non-null   str
 8   monthlycharges   7043 non-null   int64
 9   churn            7043 non-null   str
dtypes: int64(3), str(7)
memory usage: 775.3 KB

In [17]:
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(exclude=np.number).columns.tolist()

print("Numeric columns:", numeric_cols)
print("\nCategorical columns:", categorical_cols)

Numeric columns: ['seniorcitizen', 'tenure', 'monthlycharges']

Categorical columns: ['gender', 'dependents', 'phoneservice', 'multiplelines', 'internetservice', 'contract', 'churn']

In [18]:
df_clean = df.copy()

In [19]:
for col in df_clean.select_dtypes(include="object").columns:
    df_clean[col] = df_clean[col].str.strip().str.lower()

df_clean.head()

/var/folders/fr/c6p38rg92qx5f6s8cskzn4v80000gn/T/ipykernel_27497/3103809451.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_clean.select_dtypes(include="object").columns:

,gender,seniorcitizen,dependents,tenure,phoneservice,multiplelines,internetservice,contract,monthlycharges,churn
0,female,0,no,1,no,no,dsl,month-to-month,25,yes
1,male,0,no,41,yes,no,dsl,one year,25,no
2,female,0,yes,52,yes,no,dsl,month-to-month,19,no
3,female,0,no,1,yes,no,dsl,one year,76,yes
4,male,0,no,67,yes,no,fiber optic,month-to-month,51,no

In [20]:
for col in df_clean.select_dtypes(include="object").columns:
    print(f"\n--- {col} ---")
    print(df_clean[col].value_counts(dropna=False))

--- gender ---
gender
male      3555
female    3488
Name: count, dtype: int64

--- dependents ---
dependents
no     4933
yes    2110
Name: count, dtype: int64

--- phoneservice ---
phoneservice
yes    6361
no      682
Name: count, dtype: int64

--- multiplelines ---
multiplelines
no     4072
yes    2971
Name: count, dtype: int64

--- internetservice ---
internetservice
dsl            3947
fiber optic    3096
Name: count, dtype: int64

--- contract ---
contract
month-to-month    3875
two year          1695
one year          1473
Name: count, dtype: int64

--- churn ---
churn
no     5174
yes    1869
Name: count, dtype: int64

/var/folders/fr/c6p38rg92qx5f6s8cskzn4v80000gn/T/ipykernel_27497/256324143.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df_clean.select_dtypes(include="object").columns:

In [21]:
X = df_clean.drop("churn", axis=1)
y = df_clean["churn"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (7043, 9)
y shape: (7043,)

In [22]:
y = y.map({"no": 0, "yes": 1})
y.head()

0    1
1    0
2    0
3    1
4    0
Name: churn, dtype: int64

In [23]:
y.value_counts()

churn
0    5174
1    1869
Name: count, dtype: int64

In [24]:
numeric_features = ["seniorcitizen", "tenure", "monthlycharges"]
categorical_features = ["gender", "dependents", "phoneservice", "multiplelines", "internetservice", "contract"]

print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)

Numeric features: ['seniorcitizen', 'tenure', 'monthlycharges']
Categorical features: ['gender', 'dependents', 'phoneservice', 'multiplelines', 'internetservice', 'contract']

In [25]:
X_encoded = pd.get_dummies(X, columns=categorical_features, drop_first=True)
X_encoded.head()

,seniorcitizen,tenure,monthlycharges,gender_male,dependents_yes,phoneservice_yes,multiplelines_yes,internetservice_fiber optic,contract_one year,contract_two year
0,0,1,25,False,False,False,False,False,False,False
1,0,41,25,True,False,True,False,False,True,False
2,0,52,19,False,True,True,False,False,False,False
3,0,1,76,False,False,True,False,False,True,False
4,0,67,51,True,False,True,False,True,False,False

In [26]:
X_encoded.shape

(7043, 10)

In [27]:
X_encoded.columns.tolist()

['seniorcitizen',
 'tenure',
 'monthlycharges',
 'gender_male',
 'dependents_yes',
 'phoneservice_yes',
 'multiplelines_yes',
 'internetservice_fiber optic',
 'contract_one year',
 'contract_two year']

In [28]:
final_df = X_encoded.copy()
final_df["churn"] = y

final_df.head()

,seniorcitizen,tenure,monthlycharges,gender_male,dependents_yes,phoneservice_yes,multiplelines_yes,internetservice_fiber optic,contract_one year,contract_two year,churn
0,0,1,25,False,False,False,False,False,False,False,1
1,0,41,25,True,False,True,False,False,True,False,0
2,0,52,19,False,True,True,False,False,False,False,0
3,0,1,76,False,False,True,False,False,True,False,1
4,0,67,51,True,False,True,False,True,False,False,0

In [29]:
final_df.shape

(7043, 11)

In [30]:
final_df.dtypes

seniorcitizen                  int64
tenure                         int64
monthlycharges                 int64
gender_male                     bool
dependents_yes                  bool
phoneservice_yes                bool
multiplelines_yes               bool
internetservice_fiber optic     bool
contract_one year               bool
contract_two year               bool
churn                          int64
dtype: object

In [31]:
bool_cols = final_df.select_dtypes(include="bool").columns
final_df[bool_cols] = final_df[bool_cols].astype(int)

final_df.dtypes

seniorcitizen                  int64
tenure                         int64
monthlycharges                 int64
gender_male                    int64
dependents_yes                 int64
phoneservice_yes               int64
multiplelines_yes              int64
internetservice_fiber optic    int64
contract_one year              int64
contract_two year              int64
churn                          int64
dtype: object

In [32]:
final_df.to_csv("../data/processed/churn_processed.csv", index=False)
print("Processed dataset saved successfully.")

Processed dataset saved successfully.

In [33]:
df_processed = pd.read_csv("../data/processed/churn_processed.csv")
df_processed.head()

,seniorcitizen,tenure,monthlycharges,gender_male,dependents_yes,phoneservice_yes,multiplelines_yes,internetservice_fiber optic,contract_one year,contract_two year,churn
0,0,1,25,0,0,0,0,0,0,0,1
1,0,41,25,1,0,1,0,0,1,0,0
2,0,52,19,0,1,1,0,0,0,0,0
3,0,1,76,0,0,1,0,0,1,0,1
4,0,67,51,1,0,1,0,1,0,0,0

In [34]:
df_processed.shape

(7043, 11)

In [35]:
df_processed.isnull().sum().sum()

np.int64(0)